#!/usr/bin/python

import sys
import json
import simplejson
import jsonschema


schema = open("schema.json").read()

# Read data from payload.json
data = open("payload.json.bk").read()

print(json.dumps(data, indent=4))


jsonschema.validate(simplejson.loads(data), simplejson.loads(schema))

'''
try:
	jsonschema.validate(json.loads(data), json.loads(schema))
except jsonschema.exceptions.ValidationError as ve:
	sys.stderr.write("###############################\n")
        sys.stderr.write(str(ve) + "\n")
'''
